services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bank_cards_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Application
  app:
    build: .
    container_name: bank-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_cards_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: my-super-secure-jwt-secret-key-minimum-256-bits-change-this
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # PGAdmin - веб-интерфейс для управления БД
  pgadmin:
    image: dpage/pgadmin4
    container_name: bank-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: my@bank.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres_data: