#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: bank

  datasourse:
    url: jdbc:postgresql://localhost:5432/bank_system
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
      enabled: true

    security:
      oauth2:
        resourceserver:
          jwt:
            secret-key: ${JWT_SECRET:my-super-secure-jwt-secret-key-minimum-256-bits}

  jwt:
    secret: ${JWT_SECRET:my-super-secure-jwt-secret-key-minimum-256-bits}
    expiration: 86400000 # 24 hours in milliseconds

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    show-actuator: true

  logging:
    level:
      com.bank: DEBUG
      org.springframework.security: DEBUG
      org.hibernate.SQL: DEBUG



